Newsletter november 2020
subnero1/subnero1.github.io pull request #132
Opened 2020-12-09 08:14 UTC by Florie25

2020-12-10 08:03 UTC, AnneThKu commented
Updated image size and background. Screenshot given below.

![image](https://user-images.githubusercontent.com/42397354/101738491-295e8b00-3b01-11eb-8215-25b23a0fac80.png)

2020-12-10 08:03 UTC, AnneThKu approved these changes

2020-12-11 02:58 UTC, notthetup requested changes

2020-12-11 02:58 UTC, notthetup commented on _posts/2020-11-18-UnetStack-Newsletter.md
> +Read all about in the [UnetStack handbook](https://unetstack.net/handbook){:target="_blank"} (section 15.4).
```suggestion
Read all about in [section 15.4 of UnetStack handbook](https://unetstack.net/handbook/unet-handbook_physical_service.html#_transmitting_receiving_using_unet_audio){:target="_blank"}.
```

2020-12-11 02:58 UTC, notthetup commented on _posts/2020-11-18-UnetStack-Newsletter.md
> +![]({{site.baseurl}}/images/pulse-unetaudio01.jpg){: .center-image  }
```suggestion
![](/images/pulse-unetaudio01.jpg){: .center-image  }
```

2020-12-14 09:03 UTC, merged