NITK presentations
subnero1/subnero1.github.io pull request #138
Opened 2021-01-11 09:48 UTC by Florie25

Hi Anne,
Could you please have a quick look and let me know if anything needs to be changed before I assign Manu and Chinmay.

Thank you
Florie

2021-01-11 10:38 UTC, AnneThKu requested changes

2021-01-11 10:38 UTC, AnneThKu commented on _posts/2020-12-17-Subnero-talks-at-the-Open-source-Network-Experimentation.md
> +For the second year consecutive, the Subnero team attended the virtual workshop organised by the [Department of Computer Science & Engineering of the National Institute of Technology Karnataka](https
```suggestion
For the second consecutive year, the Subnero team attended the virtual workshop organised by the [Department of Computer Science & Engineering of the National Institute of Technology Karnataka](https://cse.nitk.ac.in/){:target="_blank"}.
```

2021-01-11 10:38 UTC, AnneThKu commented on _posts/2020-12-17-Subnero-talks-at-the-Open-source-Network-Experimentation.md
> +The objectives of the workshop were to give participants an understanding of the basics of underwater communications, to build underwater communication topologies and setting up simulationsin UnetSta
```suggestion
The objectives of the workshop were to give participants an understanding of the basics of underwater communications, to build underwater communication topologies and setting up simulations in UnetStack amongst others.
```

2021-01-11 10:38 UTC, AnneThKu commented on _posts/2020-12-17-Subnero-talks-at-the-Open-source-Network-Experimentation.md
> +To that effect, on Wednesday 16th of December, Dr Shiraz Shahabudeen did an overview of underwater communications, whilst Ms Florie Mancel talked about Subnero modems and solutions.
```suggestion
To that effect, on Wednesday 16th of December, [Dr Shiraz Shahabudeen](https://subnero.com/people/shiraz/) did an overview of underwater communications, whilst Ms Florie Mancel talked about Subnero modems and solutions.
```

2021-01-11 10:38 UTC, AnneThKu commented on _posts/2020-12-17-Subnero-talks-at-the-Open-source-Network-Experimentation.md
> +On Thursday 17th of December, Dr Prasad Anjangi did a presentation on underwater protocols layers.
```suggestion
On Thursday 17th of December, [Dr Prasad Anjangi](https://subnero.com/people/prasad/) did a presentation on underwater protocols layers.
```

2021-01-12 05:22 UTC, AnneThKu approved these changes

2021-01-20 03:52 UTC, notthetup approved these changes

2021-01-20 03:53 UTC, merged