Oceans global
subnero1/subnero1.github.io pull request #139
Opened 2021-01-11 10:00 UTC by Florie25

Hi Anne,

As per the previous request, please have a quick look to see if there is anything dramatically wrong.

Cheers
Florie

2021-01-11 10:38 UTC, AnneThKu requested changes

2021-01-11 10:38 UTC, AnneThKu commented on _posts/2020-10-12-Global-Oceans-2020.md
> +To make sure that we don't miss the exciting new papers and stay up to date with the latest development, the IEEE OES decided to combined Oceans Singapore and US Gulf coast into a single virtual even
```suggestion
To make sure that we don't miss the exciting new papers and stay up to date with the latest development, the IEEE OES decided to combine Oceans Singapore and US Gulf coast into a single virtual event: [Global Oceans 2020](https://global20.oceansconference.org/){:target="_blank"}.
```

2021-01-11 10:38 UTC, AnneThKu commented on _posts/2020-10-12-Global-Oceans-2020.md
> +The Subnero team was very pleased to deliver a tutorial about practical underwater software-defined network. The team talked about the fundamentals of underwater communications and networking, and ma
```suggestion
The Subnero team was very pleased to deliver a tutorial about practical underwater software-defined network. The team talked about the fundamentals of underwater communications and networking, and many practical tools and techniques to solve common challenges. In the hands-on sessions, participants were able to try out the demos themselves using the freely available [UnetStack](https://unetstack.net/){:target="_blank"} networking stack and [simulator](https://unetstack.net/handbook/unet-handbook_part_vi_simulating_underwater_networks.html){:target="_blank"}.
```

2021-01-11 10:38 UTC, AnneThKu commented on _posts/2020-10-12-Global-Oceans-2020.md
> +The session took place virtually with a serie of 6 videos:
```suggestion
The session took place virtually with a series of 6 videos:
```

2021-01-19 06:31 UTC, AnneThKu approved these changes

2021-01-20 03:53 UTC, notthetup approved these changes

2021-01-20 03:54 UTC, merged