Create 2021-05-10-Diver-com-paper.md
subnero1/subnero1.github.io pull request #158
Opened 2021-05-10 04:12 UTC by Florie25

2021-05-10 06:04 UTC, Florie25 commented
Hi @AnneThKu , could you check this PR before the one for the UnetStack release, as @esthertanhj needs it for social media for this week.
Thank you
Florie

2021-05-10 09:03 UTC, manuignatius commented on _posts/2021-05-10-Diver-com-paper.md
> +We are very proud to announce that the our paper about [Diver communication and localization paper](https://ieeexplore.ieee.org/abstract/document/9389462) has been published by IEEE Xplore.
```suggestion
We are proud to share that the our paper about [Diver communication and localization solution](https://ieeexplore.ieee.org/abstract/document/9389462) has been published in IEEE Xplore.
```

2021-05-10 09:15 UTC, manuignatius requested changes

2021-05-10 09:15 UTC, manuignatius commented on _posts/2021-05-10-Diver-com-paper.md
> +The paper is the fruit of several months of work across the Subnero team and the collaboration of [Professor Mandar Chitre](https://arl.nus.edu.sg/people/mandar-chitre/){:target="_blank"}, of the [Ac
```suggestion
The paper is the fruit of several months of work by the Subnero team, in collaboration with [Dr. Mandar Chitre](https://arl.nus.edu.sg/people/mandar-chitre/){:target="_blank"}, of the [Acoustic Research Laboratories (ARL)](https://arl.nus.edu.sg/){:target="_blank"},
```

2021-05-10 09:15 UTC, manuignatius commented on _posts/2021-05-10-Diver-com-paper.md
> +As the title indicates, the team has developed on an underwater communication system to improve divers safety using our off the shelf software-defined as well as newly designed devices.
```suggestion
As the title indicates, the team used our software-defined underwater acoustic communication and localization technology to develop a diver communication and localization system to improve operational safety of underwater divers.
```

2021-05-10 09:15 UTC, manuignatius commented on _posts/2021-05-10-Diver-com-paper.md
> +title: Diver communication and localization paper published
```suggestion
title: Diver Communication and Localization System using Underwater Acoustics
```

2021-05-10 09:15 UTC, manuignatius commented on _posts/2021-05-10-Diver-com-paper.md
> +thumbnail: images/pulse-thumbnail-Diver-Comm-05-2021.jpg
Please correct the filename to have all lower case letters

2021-05-10 09:15 UTC, manuignatius commented on _posts/2021-05-10-Diver-com-paper.md
> +The paper was presented virtually by Dr Prasad Anjangi during [Oceans 2020](https://global20.oceansconference.org/) back in October 2020.
```suggestion
The paper was presented virtually by Dr. Prasad Anjangi during [Global Oceans 2020](https://global20.oceansconference.org/) back in October 2020.
```

2021-05-10 11:09 UTC, AnneThKu requested changes

2021-05-10 11:09 UTC, AnneThKu commented on _posts/2021-05-10-Diver-com-paper.md
> +We are proud to share that our paper titled [_Diver Communication and Localization System using Underwater Acoustics_](https://ieeexplore.ieee.org/abstract/document/9389462) has been published in IEE
```suggestion
We are proud to share that our paper titled [_Diver Communication and Localization System using Underwater Acoustics_](https://ieeexplore.ieee.org/abstract/document/9389462){:target="_blank"} has been published in IEEE Xplore.
```

2021-05-10 11:09 UTC, AnneThKu commented on _posts/2021-05-10-Diver-com-paper.md
> +The paper was presented virtually by Dr. Prasad Anjangi during [Global Oceans 2020](https://global20.oceansconference.org/) back in October 2020.
```suggestion
The paper was presented virtually by [Dr. Prasad Anjangi](https://subnero.com/people/prasad/) during [Global Oceans 2020](https://global20.oceansconference.org/) back in October 2020.
```

2021-05-10 11:09 UTC, AnneThKu commented on _posts/2021-05-10-Diver-com-paper.md
> +The paper was presented virtually by Dr. Prasad Anjangi during [Global Oceans 2020](https://global20.oceansconference.org/) back in October 2020.
Do we have the link for the presentation? If so, maybe that would be more relevant than the given oceans link.

2021-05-10 11:09 UTC, AnneThKu commented on _posts/2021-05-10-Diver-com-paper.md
> +For more details, dowlonad the paper in the link above or [contact us](info@subnero.com).
```suggestion
Download the full paper in the link above or [contact us](https://subnero.com/contact/) for more details.
```

2021-05-10 11:15 UTC, Florie25 commented on _posts/2021-05-10-Diver-com-paper.md
> +The paper was presented virtually by Dr. Prasad Anjangi during [Global Oceans 2020](https://global20.oceansconference.org/) back in October 2020.
The link, at the moment, is on our Gdrive. Is there a way to share it without giving access to our Drive?

2021-05-12 03:18 UTC, AnneThKu approved these changes

2021-05-12 03:26 UTC, manuignatius approved these changes

2021-05-12 03:26 UTC, merged