Sea breath
subnero1/subnero1.github.io pull request #169
Opened 2021-07-06 09:57 UTC by Florie25

Draft new Pulse post.
The .jpg image can be changed

2021-07-08 04:23 UTC, AnneThKu requested changes

2021-07-08 04:23 UTC, AnneThKu commented on _posts/2021-07-06-Subnero-SeaBreath-partnership.md
> +Subnero,  is delighted to add [SeaBreath](https://www.sea-breath.com/)to their list of business partner.
```suggestion
Subnero,  is delighted to add [SeaBreath](https://www.sea-breath.com/) to their list of business partner.
```

2021-07-08 04:23 UTC, AnneThKu commented on _posts/2021-07-06-Subnero-SeaBreath-partnership.md
> +Seabreath is based in Tokyo and will represent Subnero in Japan.
```suggestion
SeaBreath is based in Tokyo and will represent Subnero in Japan.
```

2021-07-08 04:26 UTC, AnneThKu commented
Screenshot of the post.
![image](https://user-images.githubusercontent.com/42397354/124862134-6cc19f00-dfe7-11eb-87ee-66b2bca0a8bb.png)

2021-07-08 06:08 UTC, notthetup commented
Do we need a space between `SeaBreath` and `to`?

2021-07-08 08:14 UTC, manuignatius approved these changes

2021-07-09 02:56 UTC, AnneThKu approved these changes

2021-07-09 02:57 UTC, merged