Home page text alignment
subnero1/subnero1.github.io pull request #263
Opened 2023-08-16 03:41 UTC by jjophi

Changed position and alignment of homepage news link.

2023-08-16 09:28 UTC, manuignatius requested changes
Overall looks good, 2 comments.
1. We had a small orange underline below the tagline, its gone now, was that intentional?
2. Instead of "In the News", can we have another "term" what is similar to "Whats New"? As this is about something interesting from Subnero and may not always be news-like.

For future ones, if you can add a screenshot of the change in the PR, that would also help.

2023-08-16 16:59 UTC, jjophi commented
Updated the page with these changes:
1. Underline below the tag line added back.
2. 'In the news' text changed to 'What's new?'
3. Spacing between tagline and news section is increased.

Also updated the news section to show latest three posts but showing one at a time with a transition.

![127 0 0 1_4000_](https://github.com/subnero1/subnero1.github.io/assets/20460360/86c55e1b-2d89-4c9f-b0ea-7e0fc995676d)

2023-08-16 17:27 UTC, manuignatius approved these changes, later dismissed

2023-08-17 16:57 UTC, jjophi commented
Updated the 'What's new?' section - moved it to bottom of the page.
![127 0 0 1_4000_ (1)](https://github.com/subnero1/subnero1.github.io/assets/20460360/1cd73a32-e6d0-4e91-964b-5ae15993f59d)

2023-08-17 18:11 UTC, manuignatius approved these changes

2023-08-18 02:31 UTC, merged